# Generated by Django 6.0.6 on 2026-08-17 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date')},
        ),
    ]
